import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';

const banner = `/*
THIS FILE IS AUTO-GENERATED BY esbuild.
DO NOT MANUALLY EDIT - it will be overwritten on the next build.
*/
`;

/**
 * 构建模式（第一个命令行参数）：
 *   production   —— 压缩、无 sourcemap，构建完即退出（发布用）
 *   development  —— 不压缩、内联 sourcemap，构建完即退出（一次性 dev 构建，供本地验证）
 *   缺省 / watch —— 不压缩、内联 sourcemap，监听文件变化持续重建（开发用）
 */
const mode = process.argv[2] ?? 'watch';
const prod = mode === 'production';
/** 是否「构建一次就退出」（非 watch 模式） */
const once = mode === 'production' || mode === 'development';

/** @type {import('esbuild').BuildOptions} */
const opts = {
  banner: { js: banner },
  entryPoints: ['main.ts'],
  bundle: true,
  format: 'cjs',
  target: 'es2020',
  logLevel: 'info',
  outfile: 'main.js',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  // 生产构建压缩；开发构建保持可读（合法注释如 three.js 的 MIT 声明仍会保留在文件末尾）
  minify: prod,
  external: ['obsidian', 'electron', ...builtins],
  define: {
    'process.env.NODE_ENV': JSON.stringify(prod ? 'production' : 'development')
  },
  loader: {
    '.js': 'js',
    '.ts': 'ts'
  }
};

/** @type {import('esbuild').Plugin} */
const esbuildPluginAlias = {
  name: 'alias',
  setup(build) {
    // 保留 obsidian 作为 external，避免被打包
    build.onResolve({ filter: /^obsidian$/ }, () => ({ path: 'obsidian', external: true }));
  }
};

/**
 * @param {import('esbuild').BuildOptions} o
 */
async function main(o) {
  const ctx = await esbuild.context(o);
  if (once) {
    await ctx.rebuild();
    await ctx.dispose();
  } else {
    await ctx.watch();
  }
}

main({ ...opts, plugins: [esbuildPluginAlias] }).catch((e) => {
  console.error(e);
  process.exit(1);
});
