import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';

const banner = `/*
THIS FILE IS AUTO-GENERATED BY esbuild.
DO NOT MANUALLY EDIT - it will be overwritten on the next build.
*/
`;

const prod = process.argv[2] === 'production';

/** @type {import('esbuild').BuildOptions} */
const opts = {
  banner: { js: banner },
  entryPoints: ['main.ts'],
  bundle: true,
  format: 'cjs',
  target: 'es2020',
  logLevel: 'info',
  outfile: 'main.js',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  // 生产构建压缩；开发构建保持可读（合法注释如 three.js 的 MIT 声明仍会保留在文件末尾）
  minify: prod,
  external: ['obsidian', 'electron', ...builtins],
  define: {
    __DEV__: prod ? 'false' : 'true',
    'process.env.NODE_ENV': JSON.stringify(prod ? 'production' : 'development')
  },
  loader: {
    '.js': 'js',
    '.ts': 'ts'
  }
};

process.argv.forEach((arg) => {
  if (arg === 'dev') {
    opts.watch = true;
    opts.serve = { serveHost: '127.0.0.1', servePort: 8080 };
  }
});

/** @type {import('esbuild').Plugin} */
const esbuildPluginAlias = {
  name: 'alias',
  setup(build) {
    // 保留 obsidian 作为 external，避免被打包
    build.onResolve({ filter: /^obsidian$/ }, () => ({ path: 'obsidian', external: true }));
  }
};

/**
 * @param {import('esbuild').BuildOptions} o
 */
async function main(o) {
  const ctx = await esbuild.context(o);
  if (prod) {
    await ctx.rebuild();
    await ctx.dispose();
  } else {
    await ctx.watch();
  }
}

main({ ...opts, plugins: [esbuildPluginAlias] }).catch((e) => {
  console.error(e);
  process.exit(1);
});
